### ISSUE TITLE
RedmineManager no longer implements IRedmineManager

### ISSUE THREAD

**Issue by NielsFestjens** [zapadi/redmine-net-api#203]
Hey guys

I wanted to update redmine-net-api (we currently work with 1.0.8), but apparently the new version does not implement the interface IRedmineManager anymore.
Is it possible to re-implement it?
We have unit tests where we mock out the RedmineManager since we don't want to create a Redmine issue every time a unit test runs. If we update, we'd have to create a wrapper around RedmineManager to achieve the same result.

Cheers
